/**
 * Report Generation Plugin
 * Formats and generates professional pentesting reports
 */

class ReportPlugin {
  constructor() {
    this.name = 'report-plugin';
    this.version = '1.0';
    this.enabled = false;
    this.findings = [];
    this.timestamp = new Date().toISOString();
  }

  /**
   * Parse severity level from LLM response
   */
  extractSeverity(text) {
    if (/CRITICAL/i.test(text)) return 'CRITICAL';
    if (/HIGH/i.test(text)) return 'HIGH';
    if (/MEDIUM/i.test(text)) return 'MEDIUM';
    if (/LOW/i.test(text)) return 'LOW';
    return 'INFO';
  }

  /**
   * Extract vulnerability details from response
   */
  extractVulnerabilities(response, prompt) {
    const severity = this.extractSeverity(response);
    const cveMatches = response.match(/CVE-\d{4}-\d{4,}/gi) || [];

    return {
      timestamp: new Date().toISOString(),
      query: prompt,
      severity: severity,
      description: response.substring(0, 500),
      cves: [...new Set(cveMatches)],
      raw: response,
    };
  }

  /**
   * Generate markdown report
   */
  generateMarkdownReport(findings) {
    let report = `# Penetration Testing Report\n\n`;
    report += `**Generated:** ${new Date().toISOString()}\n\n`;
    report += `## Executive Summary\n\n`;
    report += `Total Findings: ${findings.length}\n`;
    report += `Critical Issues: ${findings.filter((f) => f.severity === 'CRITICAL').length}\n`;
    report += `High Issues: ${findings.filter((f) => f.severity === 'HIGH').length}\n`;
    report += `Medium Issues: ${findings.filter((f) => f.severity === 'MEDIUM').length}\n`;
    report += `Low Issues: ${findings.filter((f) => f.severity === 'LOW').length}\n\n`;

    report += `## Detailed Findings\n\n`;

    // Group by severity
    const bySeverity = {};
    findings.forEach((f) => {
      if (!bySeverity[f.severity]) bySeverity[f.severity] = [];
      bySeverity[f.severity].push(f);
    });

    const severityOrder = ['CRITICAL', 'HIGH', 'MEDIUM', 'LOW', 'INFO'];
    severityOrder.forEach((sev) => {
      if (bySeverity[sev]) {
        report += `### ${sev} Severity\n\n`;
        bySeverity[sev].forEach((finding, idx) => {
          report += `#### ${idx + 1}. Finding\n`;
          report += `- **Timestamp:** ${finding.timestamp}\n`;
          report += `- **Query:** ${finding.query}\n`;
          report += `- **Description:** ${finding.description}\n`;
          if (finding.cves.length > 0) {
            report += `- **Related CVEs:** ${finding.cves.join(', ')}\n`;
          }
          report += `\n`;
        });
      }
    });

    report += `## Recommendations\n\n`;
    report += `1. Prioritize remediation of CRITICAL and HIGH severity findings\n`;
    report += `2. Cross-reference all identified CVEs with patches\n`;
    report += `3. Re-test after remediation\n`;
    report += `4. Document all changes for compliance\n\n`;

    report += `## Appendix\n\n`;
    report += `Generated by Kali Hacker Bot Report Plugin v1.0\n`;

    return report;
  }

  /**
   * Hook handler for after:llm-response
   */
  onLLMResponse(data) {
    if (!data.response) {
      return data;
    }

    // Extract vulnerability and store
    const vuln = this.extractVulnerabilities(data.response, data.prompt);
    this.findings.push(vuln);

    // Add report generation note
    data.response += '\n\n[📋 Report entry recorded by report-plugin]';

    return data;
  }

  /**
   * Get current findings
   */
  getFindings() {
    return this.findings;
  }

  /**
   * Reset findings
   */
  resetFindings() {
    this.findings = [];
    this.timestamp = new Date().toISOString();
  }

  /**
   * Export report as markdown
   */
  exportReport(format = 'markdown') {
    if (format === 'markdown') {
      return this.generateMarkdownReport(this.findings);
    }

    if (format === 'json') {
      return JSON.stringify(
        {
          timestamp: this.timestamp,
          totalFindings: this.findings.length,
          findings: this.findings,
        },
        null,
        2
      );
    }

    return this.findings;
  }
}

module.exports = new ReportPlugin();
